Projeto_IT2/ClienteAuth/Models/Anuncio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClienteAuth.Models
{
    public enum TipoAnuncio { Venda, Aluguer, Permuta, Compra }
    public class Anuncio
    {
        [DisplayName("Nome do Anúncio")]
        public int AnuncioID { get; set; }
        [DisplayName("Nome do Anúncio")]
        public string Nome { get; set; }
        [DisplayName("Descrição do Anúncio")]
        public string Descricao { get; set; }
        [DisplayName("Data de criação")]
        [DataType(DataType.Date)]
        public DateTime DataCriacao { get; set; }
        [DisplayName("Tipo do Anúncio")]
        public TipoAnuncio TipoAnuncio { get; set; }

        public int ImovelID { get; set; }
        public string ImovelUtilizador { get; set; }
        public string ImovelNome { get; set; }
        public string ImovelUrl { get; set; }
        public Imovel Imovel { get; set; }
     
    }
}

Projeto_IT2/ClienteAuth/Controllers/ImovelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClienteAuth.Helpers;
using System.Net.Http;
using Newtonsoft.Json;
using System.Threading.Tasks;
using ClienteAuth.Models;

namespace ClienteAuth.Controllers
{
    public class ImovelsController : Controller
    {

        // GET: Imovels
        public async Task<ActionResult> Index()
        {
            var cliente = WebApiHttpClient.GetClient();

            HttpResponseMessage response = await cliente.GetAsync("api/Imovels");
            if (response.IsSuccessStatusCode)

            {
                string content = await response.Content.ReadAsStringAsync();
                var imoveis = JsonConvert.DeserializeObject<IEnumerable<Imovel>>(content);
                return View(imoveis);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }


        }
        // GET: Imovels/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var cliente = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await cliente.GetAsync("api/Imovels/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var i = JsonConvert.DeserializeObject<Imovel>(content);
                if (i == null) return HttpNotFound();
                return View(i);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

        }

        // GET: Imovels/Create
        public async Task<ActionResult> Create()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Localizacaos");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var Localizacoes = JsonConvert.DeserializeObject<IEnumerable<Localizacao>>(content);
                ViewBag.LocalizacaoID = new SelectList(Localizacoes, "LocalizacaoID", "Nome");
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

            var client2 = WebApiHttpClient.GetClient();
            HttpResponseMessage response2 = await client2.GetAsync("api/TipoImovels");
            if (response2.IsSuccessStatusCode)
            {
                string content2 = await response2.Content.ReadAsStringAsync();
                var TiposImoveis = JsonConvert.DeserializeObject<IEnumerable<TipoImovel>>(content2);
                ViewBag.TipoImovelID = new SelectList(TiposImoveis, "TipoImovelID", "Nome");
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

            return View();
        }

        // POST: Imovels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ImovelID,Nome,Area,Preco,LocalizacaoID,TipoImovelID,Foto,Utilizador,Gps")] Imovel imovel, [Bind(Include = "Url")] Foto foto)
        {

            try
            {
                //ImovelID, Nome, Area, Preco, LocalizacaoID, TipoImovelID, FotoID, 
                //Utilizador, GPS_Latitude, GPS_Longitude

                //Associação do utilizador logado ao imóvel
                imovel.Utilizador = WebApiHttpClient.getToken().Username;

                var cliente = WebApiHttpClient.GetClient();
                string beforeJSON = JsonConvert.SerializeObject(imovel);
                
                HttpContent content = new StringContent(beforeJSON, System.Text.Encoding.Unicode, "application/json");

                var response = await cliente.PostAsync("api/Imovels", content);

                if (response.IsSuccessStatusCode) {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }

             }
            catch {
                    return Content("Ocorreu um erro.");
            }

    }

        // GET: Imovels/Edit/5
        public async  Task<ActionResult> Edit(int? id)
        {
            //Criação das ViewBags para as DropDownLists
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Localizacaos");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var Localizacoes = JsonConvert.DeserializeObject<IEnumerable<Localizacao>>(content);
                ViewBag.LocalizacaoID = new SelectList(Localizacoes, "LocalizacaoID", "Nome");
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

            var client2 = WebApiHttpClient.GetClient();
            HttpResponseMessage response2 = await client2.GetAsync("api/TipoImovels");
            if (response2.IsSuccessStatusCode)
            {
                string content2 = await response2.Content.ReadAsStringAsync();
                var TiposImoveis = JsonConvert.DeserializeObject<IEnumerable<TipoImovel>>(content2);
                ViewBag.TipoImovelID = new SelectList(TiposImoveis, "TipoImovelID", "Nome");
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var cliente3 = WebApiHttpClient.GetClient();
            HttpResponseMessage resposta3 = await cliente3.GetAsync("api/Imovels/" + id);
            if (resposta3.IsSuccessStatusCode)
            {
                string content3 = await resposta3.Content.ReadAsStringAsync();
                var imovel = JsonConvert.DeserializeObject<Imovel>(content3);
                if(imovel == null)
                    return HttpNotFound();

                return View(imovel);
            }
                return Content("Ocorreu um erro: "+ resposta3.StatusCode);
         }

        // POST: Imovels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ImovelID,Nome,Area,Preco,LocalizacaoID,TipoImovelID,FotoID,Utilizador,Longitude,Latitude")] Imovel imovel, [Bind(Include = "Url")] Foto foto)
        {
            try {
                Gps gps = new Gps() {
                    Latitude = imovel.Latitude,
                    Longitude = imovel.Longitude
                };

                imovel.Utilizador = WebApiHttpClient.getToken().Username;
                imovel.Gps = gps;
                imovel.Foto = foto;
           
                var cliente = WebApiHttpClient.GetClient();
                string beforeJSON = JsonConvert.SerializeObject(imovel);
                HttpContent content = new StringContent(beforeJSON, System.Text.Encoding.Unicode, "application/json");
                var response = await cliente.PutAsync("api/Imovels/" + imovel.ImovelID, content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");

                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch 
            {
                return Content("Ocorreu um erro.");
            }
           
        }

        // GET: Imovels/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cliente = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await cliente.GetAsync("api/Imovels/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var i = JsonConvert.DeserializeObject<Imovel>(content);
                if (i == null)
                    return HttpNotFound();
                return View(i);
            }

            return Content("Ocorreu um erro:" + response.StatusCode);
        }

        // POST: Imovels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var cliente = WebApiHttpClient.GetClient();
                var resposta = await cliente.DeleteAsync("api/Imovels/" + id);
                if (resposta.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + resposta.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        
        }

        //protected override void Dispose(bool disposing)
        //{

Projeto_IT2/ClienteAuth/Views/Anuncios/Create.cshtml
@model ClienteAuth.Models.Anuncio
@using ClienteAuth.Helpers
@{
    ViewBag.Title = "Create";
}


@if (WebApiHttpClient.getToken() != null)
{
    if (WebApiHttpClient.getToken().Role == "[\"Cliente\"]")
    {
<h2>Criar Novo Anúncio</h2>


using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Anuncio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCriacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoAnuncio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoAnuncio, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoAnuncio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImovelID, "ImovelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ImovelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImovelID, "", new { @class = "text-danger" }) @(' ') @('|') @(' ')
                @Html.ActionLink("Registar novo imóvel", "Create", "Imovels") 
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    }
}
<div>
    @Html.ActionLink("Voltar à Lista", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projeto_IT2/ClienteAuth/Views/Anuncios/Delete.cshtml
@model ClienteAuth.Models.Anuncio
@using ClienteAuth.Helpers

@{
    ViewBag.Title = "Delete";
}

@if (WebApiHttpClient.getToken() != null)
{
    if (WebApiHttpClient.getToken().Role == "[\"Cliente\"]")
    {
<h2>Delete</h2>

<h3>De certeza que deseja apagar este anúncio??</h3>
<div>
    <h4>Anuncio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imovel.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImovelNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAnuncio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAnuncio)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
  
</div>
    }
}

Projeto_IT2/ClienteAuth/Views/Anuncios/Details.cshtml
@model ClienteAuth.Models.Anuncio

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Anuncio</h4>
    <hr />


    <dl class="dl-horizontal">
        <dt> 
            @Html.DisplayNameFor(model => model.Imovel.Utilizador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImovelUtilizador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imovel.Nome)
        </dt>
            
        <dd>
            @Html.DisplayFor(model => model.ImovelNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAnuncio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAnuncio)
        </dd>

    </dl>

    @Html.ActionLink("Detalhes do imóvel",
    "Details",  // <-- Controller Name.
                     "Imovels" ,   // <-- ActionMethod
                                       new { id=Model.ImovelID }, // <-- Route arguments.
                                                                            null  // <-- htmlArguments .. which are none. You need this value
                      //     otherwise you call the WRONG method ...
    //     (refer to comments, below).
    )

</div>
<p>
    @Html.ActionLink("Voltar à Lista", "Index")
</p>

Projeto_IT2/ClienteAuth/Views/Anuncios/Edit.cshtml
@model ClienteAuth.Models.Anuncio
@using ClienteAuth.Helpers
@{
    ViewBag.Title = "Editar";
}


@if (WebApiHttpClient.getToken() != null)
{
    if (WebApiHttpClient.getToken().Role == "[\"Cliente\"]")
    {
<h2>Editar</h2>


        using (Html.BeginForm())
        {

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Anuncio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AnuncioID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCriacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoAnuncio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoAnuncio, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoAnuncio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImovelID, "ImovelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ImovelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImovelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
        }
<div>
    @Html.ActionLink("Voltar à Lista", "Index")
</div>
    }
}

<h2>Anúncios</h2>
<br />


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projeto_IT2/ClienteAuth/Views/Anuncios/Index.cshtml
@model IEnumerable<ClienteAuth.Models.Anuncio>
@using ClienteAuth.Helpers
@{
    ViewBag.Title = "Index";
}

<h2>Anúncios</h2>
@if (WebApiHttpClient.getToken() != null)
{
    if (WebApiHttpClient.getToken().Role == "[\"Cliente\"]")
    {
<p>
    @Html.ActionLink("Criar Novo Anuncio", "Create")
</p>
    }
}
<table class="table">
@if (!Model.Any())
{
    <tr><td>Não existem Anúncios.</td></tr>
}
else
{
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Imovel.Foto.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImovelNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoAnuncio)
        </th>
        <th></th>
    </tr>

    foreach (var item in Model)
    {
    <tr>

        <td>
            <img src="@Url.Content(item.ImovelUrl)" alt="Image" height="80" width="60" onError="this.onerror=null; this.src = 'https://image.freepik.com/free-icon/rural-hotel-house-with-birds-and-clouds_318-51246.png'" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImovelNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataCriacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoAnuncio)
        </td>
        <td>
        @if (WebApiHttpClient.getToken() != null)
        {
            if (WebApiHttpClient.getToken().Username.Equals(item.ImovelUtilizador))
            {
                @Html.ActionLink("Editar", "Edit", new { id = item.AnuncioID }) @(' ') @('|') @(' ')
                @Html.ActionLink("Apagar", "Delete", new { id = item.AnuncioID }) @(' ') @('|') @(' ')
            }
        }
        @Html.ActionLink("Detalhes", "Details", new { id = item.AnuncioID }) 
          
        </td>
    </tr>
    }
}

</table>